# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mysql
    image: inf23dw1g24/mysql
    build:
      context: .
      dockerfile: ./dockerfile.database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - user-network
    ports:
      - "3306:3306"


  api:
    container_name: api
    image: inf23dw1g24/api
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9999:9999
    networks:
      - user-network
      
networks:
  user-network: