# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: ./dockerfile.database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - user-network
    ports:
      - "3306:3306"
      
networks:
  user-network: